name: quickstart
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  dotenv: ^3.0.0
  google_generative_ai: ^0.4.4
  shelf: ^1.4.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0